### ISSUE TITLE
Nan divisor in "combine_patches"

### ISSUE THREAD

**Issue by Yuval-H** [iyttor/GPNN#1]
Hello,First, great code, thanks!

In "combine_patches" - the returned results is = combined / divisor.

For some of the images, some elements of the divisor equal to zero. This results in Nan elements in the final combined image, leading to wrong output image.I did not go into the mathematics of the image recovery phase, would it be correct to replace the zero divisor with some other big/small number?

Is this a bug or incorrect use of the algorithm?

thanks!

**Comment by iyttor** [comment]
Generally, the divisor is always positive.
What is the task and parameters? What is the input?

בתאריך יום ג׳, 22 ביוני 2021, 12:42, מאת YuvalH ***@***.***>:

**Comment by Yuval-H** [comment]
The task is structural_analogies,  
The parameters are: coarse_dim=50, stride=3, all other are the defaults.
The input is 384*384 rgb image.

Thanks for the quick reply

**Comment by iyttor** [comment]
Couldn't reproduce your issue, though added a line of code to address it.
Let me know if it's not fixed yet.
